[package]
name = "nightcycle/page-service"
description = "A foundation for player HUD / page navigation"
version = "2.0.1"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
ColdFusion = "nightcycle/cold-fusion@9.0.7"
Signal = "nightcycle/signal@1.0.2"
Maid = "nightcycle/maid@1.1.4"
Synthetic = "nightcycle/synthetic@6.0.2"
GeometryUtil = "nightcycle/geometry-util@1.1.1"
TableUtil = "nightcycle/table-util@1.1.0"
FormatUtil = "nightcycle/format-util@1.0.0"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
GuiLibrary = "nightcycle/gui-library@3.0.1"
Spring = "nightcycle/spring@1.0.0"
