[package]
name = "nightcycle/page-service"
description = "A foundation for player HUD / page navigation"
version = "2.0.1"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Synthetic = "nightcycle/synthetic-react@11.1.7"
Maid = "nightcycle/maid@2.2.2"
ServiceProxy = "nightcycle/service-proxy@1.0.5"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
MaterialIcons = "nightcycle/material-icons-default-dp24-1x@1.0.3"
OutlinedMaterialIcons = "nightcycle/material-icons-outlined-dp24-1x@1.0.3"