[package]
name = "nightcycle/page-service"
description = "A foundation for player HUD / page navigation"
version = "2.0.1"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
ColdFusion = "nightcycle/cold-fusion@9.0.7"
Maid = "nightcycle/maid@1.1.4"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
