name: Validate Commit

on:
  push:
    branches:
      - main

jobs:

  validate:
    runs-on: windows-latest

    strategy:
      matrix:
        scene: [main]
        include:
          - name: main

    env:
      ROJO_CONFIG: default.project.json
      LC_ALL: C.UTF-8  # Set the locale to UTF-8
      LANG: C.UTF-8    # Set the language to UTF-8
    steps:
      - uses: actions/checkout@v2

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: run code-gen
        run: sh scripts/code-gen.sh

      - name: lint and typecheck
        run: sh scripts/validate.sh ${{env.ROJO_CONFIG}} --download

